apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  labels:
    app: notes-app
spec:
  selector:
    app: notes-app
    deployment: blue
  ports:
  - name: http
    port: 80
    targetPort: 3000